const syllabus = {
  maths: [
    { topic: "Interest", remaining: 8 },
    { topic: "Time & Work", remaining: 6 },
    { topic: "Speed, Time & Distance", remaining: 7 },
    { topic: "Number System", remaining: 10 },
    { topic: "Square - Square Roots", remaining: 3 },
    { topic: "Indices & Surds", remaining: 3 },
    { topic: "Decimal & Fraction", remaining: 3 },
    { topic: "Simplification", remaining: 4 },
    { topic: "Percentage", remaining: 7 },
    { topic: "Profit & Loss", remaining: 8 },
    { topic: "L.C.M. & H.C.F.", remaining: 5 },
    { topic: "Algebra", remaining: 5 },
    { topic: "Mensuration", remaining: 3 }
  ],

  reasoning: [
    { topic: "Syllogism", remaining: 2 },
    { topic: "Statement & Conclusion", remaining: 1 },
    { topic: "Statement & Assumption", remaining: 1 },
    { topic: "Assertion & Reason", remaining: 1 },
    { topic: "Mirror Images & Water Image", remaining: 2 },
    { topic: "Paper Cutting", remaining: 1 },
    { topic: "Counting Figure", remaining: 2 },
    { topic: "Non Verbal Series", remaining: 1 },
    { topic: "Dice", remaining: 2 },
    { topic: "Venn Diagram", remaining: 2 },
    { topic: "Arithmetical Reasoning", remaining: 3 },
    { topic: "Problem Solving", remaining: 2 },
    { topic: "Coding Decoding", remaining: 4 },
    { topic: "Series", remaining: 4 },
    { topic: "Analogy", remaining: 3 },
    { topic: "Classification", remaining: 2 },
    { topic: "Calendar", remaining: 4 }
  ],

  staticGK: [
    { topic: "Organizations", remaining: 6 },
    { topic: "Art & Culture", remaining: 7 },
    { topic: "Books & Authors", remaining: 1 },
    { topic: "Country, Currency & Parliament", remaining: 2 },
    { topic: "Important Days & Theme", remaining: 4 },
    { topic: "State Special", remaining: 4 },
    { topic: "First in India & World", remaining: 2 },
    { topic: "National Schemes", remaining: 2 },
    { topic: "Award", remaining: 6 },
    { topic: "Sports", remaining: 2 },
    { topic: "Environment & Ecology", remaining: 8 },
    { topic: "Dance", remaining: 6 },
    { topic: "Festival", remaining: 1 }
  ],

  science: [
    { topic: "Environment", remaining: 2 },
    { topic: "Nutrition", remaining: 1 },
    { topic: "Vitamin & Mineral", remaining: 2 },
    { topic: "Human Digestive System", remaining: 3 },
    { topic: "Human Circulatory System", remaining: 3 },
    { topic: "Nervous System", remaining: 2 },
    { topic: "Endocrine System", remaining: 2 },
    { topic: "Skeleton System", remaining: 2 },
    { topic: "Reproductive System", remaining: 3 },
    { topic: "Excretory System", remaining: 2 },
    { topic: "Respiratory System", remaining: 2 },
    { topic: "Cell", remaining: 2 },
    { topic: "Human Disease", remaining: 3 },
    { topic: "Plant Hormone", remaining: 1 },
    { topic: "Genetics", remaining: 2 },
    { topic: "Diversity in Living Organisms", remaining: 4 },
    { topic: "Matter in our Surrounding", remaining: 2 },
    { topic: "Structure of an Atom", remaining: 1 },
    { topic: "Periodic Table", remaining: 2 },
    { topic: "Chemical Reaction & Equation", remaining: 2 },
    { topic: "Carbon & Its Compound", remaining: 2 },
    { topic: "Acid, Base & Salts", remaining: 2 },
    { topic: "Metals & Non - Metals", remaining: 2 },
    { topic: "Chemistry in Everyday Life", remaining: 2 },
    { topic: "Basic Concept of Chemistry", remaining: 1 },
    { topic: "Units & Dimension", remaining: 2 },
    { topic: "Measuring Instruments", remaining: 1 },
    { topic: "Optics", remaining: 4 },
    { topic: "Human Eye", remaining: 1 },
    { topic: "Motion", remaining: 1 },
    { topic: "Laws of Motion", remaining: 2 },
    { topic: "Work, Energy & Power", remaining: 2 },
    { topic: "Heat & Thermodynamics", remaining: 2 },
    { topic: "Gravitation", remaining: 1 },
    { topic: "Fluid & Friction", remaining: 3 },
    { topic: "Electricity", remaining: 3 },
    { topic: "Magnetism", remaining: 2 },
    { topic: "Cell Division", remaining: 1 },
    { topic: "Plant Tissue", remaining: 1 },
    { topic: "Animal Tissue", remaining: 2 },
    { topic: "Human Heart", remaining: 1 }
  ],

  history: [
    { topic: "Marathas", remaining: 2 },
    { topic: "Vijay Nagar Empire", remaining: 2 },
    { topic: "Bhakti Movement", remaining: 1 },
    { topic: "Indus Valley Civilization", remaining: 3 },
    { topic: "Vedic Age", remaining: 3 },
    { topic: "Mahajanapadas", remaining: 1 },
    { topic: "Buddhism", remaining: 1 },
    { topic: "Jainism", remaining: 1 },
    { topic: "Buddhism & Jainism Similarities / Differences", remaining: 1 },
    { topic: "Haryanka & Shishunaga Dynasty", remaining: 1 },
    { topic: "Nanda Dynasty & Pre Mauryan Period", remaining: 1 },
    { topic: "Mauryan Period", remaining: 1 },
    { topic: "Post Mauryan Period", remaining: 1 },
    { topic: "Post Mauryan Period & Pre Gupta Period", remaining: 1 },
    { topic: "Gupta Period", remaining: 3 },
    { topic: "Sangam Period", remaining: 1 },
    { topic: "Cholas, Cheras & Pandyas", remaining: 1 },
    { topic: "Pre History, Proto History & History", remaining: 1 },
    { topic: "Arrival of Europeans", remaining: 3 },
    { topic: "Battle of Plassey & Buxar", remaining: 2 },
    { topic: "Mysore, Subsidiary Alliance", remaining: 2 },
    { topic: "Maratha Wars", remaining: 2 },
    { topic: "Sikh", remaining: 1 },
    { topic: "Doctrine of Lapse", remaining: 1 },
    { topic: "Land Revenue System", remaining: 1 },
    { topic: "Socio-Religious Reforms", remaining: 3 },
    { topic: "1857 Revolt", remaining: 2 },
    { topic: "National Movement", remaining: 13 },
    { topic: "Arabic & Turkish Invasion of India", remaining: 1 },
    { topic: "Delhi Sultanate", remaining: 5 },
    { topic: "Mughal Dynasty", remaining: 7 },
    { topic: "Sur Dynasty", remaining: 1 }
  ],

  currentAffairs: [
    { topic: "Current Affairs", remaining: 14 }
  ],

  biharGK: [
    { topic: "Bihar : An Introduction", remaining: 1 },
    { topic: "History of Bihar", remaining: 6 },
    { topic: "Geography of Bihar", remaining: 5 },
    { topic: "Polity of Bihar", remaining: 3 },
    { topic: "Economy of Bihar", remaining: 1 },
    { topic: "Agriculture in Bihar", remaining: 1 },
    { topic: "Census of Bihar", remaining: 1 },
    { topic: "Art & Culture in Bihar (Folk Drama, Folk Dance, Folk Songs)", remaining: 1 },
    { topic: "Major Fairs & Festivals of Bihar", remaining: 1 },
    { topic: "National Parks & Wildlife Sanctuaries in Bihar", remaining: 1 },
    { topic: "Minerals in Bihar", remaining: 1 }
  ],

  geography: [
    { topic: "Geographical Introduction of India", remaining: 5 },
    { topic: "Hill Region of the North", remaining: 4 },
    { topic: "Peninsular India", remaining: 2 },
    { topic: "Plateaus of India", remaining: 1 },
    { topic: "Major Rivers of India", remaining: 6 },
    { topic: "Lakes of India", remaining: 1 },
    { topic: "Waterfalls of India", remaining: 1 },
    { topic: "India's Multipurpose Project", remaining: 1 },
    { topic: "Mineral Resources", remaining: 2 },
    { topic: "Energy Resources", remaining: 2 },
    { topic: "Major Industries", remaining: 1 },
    { topic: "Forest Resources Report", remaining: 1 },
    { topic: "Agriculture of India", remaining: 1 },
    { topic: "Tribes of India", remaining: 1 },
    { topic: "Major Rivers of the World", remaining: 1 },
    { topic: "Major Mountains of the World", remaining: 1 },
    { topic: "Major International Borders of the World", remaining: 1 },
    { topic: "Solar System", remaining: 1 }
  ],

  polity: [
    { topic: "Constitutional History", remaining: 2 },
    { topic: "Cabinet Mission", remaining: 1 },
    { topic: "Constitution Assembly", remaining: 1 },
    { topic: "Parts of Constitution", remaining: 1 },
    { topic: "Schedules", remaining: 1 },
    { topic: "Union of India", remaining: 1 },
    { topic: "Citizenship", remaining: 2 },
    { topic: "Fundamental Rights", remaining: 4 },
    { topic: "DPSP", remaining: 2 },
    { topic: "Fundamental Duties", remaining: 1 },
    { topic: "President", remaining: 2 },
    { topic: "Vice President", remaining: 1 },
    { topic: "Prime Minister", remaining: 2 },
    { topic: "Attorney General", remaining: 1 },
    { topic: "Parliament", remaining: 5 },
    { topic: "Governor", remaining: 1 },
    { topic: "Chief Minister", remaining: 1 },
    { topic: "State Legislature", remaining: 3 },
    { topic: "Supreme Court", remaining: 2 },
    { topic: "High Court", remaining: 2 },
    { topic: "Centre State Relation", remaining: 3 },
    { topic: "All India Service", remaining: 1 },
    { topic: "UPSC", remaining: 1 },
    { topic: "Election Commission", remaining: 1 },
    { topic: "Official Language", remaining: 1 },
    { topic: "Emergency Provision", remaining: 1 },
    { topic: "Commissions", remaining: 1 },
    { topic: "Panchayati Raj", remaining: 3 }
  ],

  economics: [
    { topic: "Type of Market", remaining: 1 },
    { topic: "Inflation & Its Related Terms", remaining: 2 },
    { topic: "Poverty", remaining: 1 },
    { topic: "Unemployment", remaining: 1 },
    { topic: "Indian Banking System", remaining: 2 },
    { topic: "Reserve Bank of India", remaining: 2 },
    { topic: "Monetary Policy", remaining: 2 },
    { topic: "Basics of Economics", remaining: 2 },
    { topic: "Economic Planning in India", remaining: 2 },
    { topic: "Niti Aayog", remaining: 1 },
    { topic: "Public Finance of India (Budget)", remaining: 2 },
    { topic: "National Income", remaining: 2 },
    { topic: "Money Market", remaining: 1 },
    { topic: "Capital Market", remaining: 2 },
    { topic: "Currency", remaining: 1 },
    { topic: "Census", remaining: 2 },
    { topic: "Agriculture", remaining: 1 },
    { topic: "Banking Terminology", remaining: 1 },
    { topic: "Agriculture", remaining: 1 }
  ]
};
